from selenium import webdriver
from pythonProjectSmartway.pages.avia_page import SmartwayLoginPage, Search_Avia, Filter, CartPage, RefundPage, Check

driver = webdriver.Chrome()
smartway_page = SmartwayLoginPage(driver)
smartway_page.open_smartway_url()
smartway_page.log_in("v.vahmistrov@smartway.today", "111111")
smartway_page.check_balance()
search = Search_Avia(driver)
search.money()
search.search_flight("Сочи", "Москва")
filter_page = Filter(driver)
filter_page.wait_for_refund_filter()
filter_page.click_refund_filter()
filter_page.click_add_to_cart()
filter_page.wait_for_notification_added()
filter_page.click_notification_added()
filter_page.wait_for_cart_loaded()
card = CartPage(driver)
card.select_employee("Вахмистров Виталий")
card.check_fields_filled()
card.proceed_to_payment()
card.is_duplicate_in_cart()
card.close_duplicate_agreement()
card.finish_accept_rules()
card.is_agreement_double_correct()
card.click_buy_button()
card.verify_payment_success()
refund_page = RefundPage(driver)
refund_page.open_trip()
refund_page.calculate_refund()
refund_page.wait_for_approval_element()
refund_page.click_approval()
refund_page.refund_ticket()
refund_page.confirm_refund()
refund_page.wait_for_process_complete()
refund_page.check_status()
search_avia_object = Search_Avia(driver)
check = Check(driver, search_avia_object)
check.check_delta_balance()
refund_page.wait_for_process_complete()
refund_page.check_status()
