from selenium.webdriver.common.by import By


class Locators:
    EMAIL = (By.CSS_SELECTOR, 'input[type="email"]')
    PASSWORD = (By.CSS_SELECTOR, 'input[type="password"]')
    BUTTON_LINK = (By.CSS_SELECTOR, '[type="button"]')
    BALANCE = (By.CSS_SELECTOR, '[class="_wrapper_1i2j8_1 _default_1i2j8_2"]')
    AVIA_BUTTON = (By.CSS_SELECTOR, '[data-qa="smartdesk-search-panel-searchAirline"]')
    DEPARTURE_CITY = (By.CSS_SELECTOR, '[data-qa="search-airline-panel-city-from"]')
    CITY_FROM_FIRST_EL = (By.CSS_SELECTOR, '[data-qa="search-airline-panel-city-from-first-el"]')
    ARRIVAL_CITY = (By.CSS_SELECTOR, '[data-qa="search-airline-panel-city-to"]')
    CITY_TO_FIRST_EL = (By.CSS_SELECTOR, '[data-qa="search-airline-panel-city-to-first-el"]')
    INPUT_DATE = (By.CSS_SELECTOR, '[data-qa="search-airline-panel-date-from"]')
    SEARCH_BUTTON = (By.CSS_SELECTOR, '[data-qa="search-airline-panel-search-button"]')
    REFUND_FILTER = (By.CSS_SELECTOR, '[data-qa="search-airline-filters-refundable-with-charge"]')
    ADD_TO_CART_BUTTON = (By.CSS_SELECTOR, '[data-qa="search-airline-button-cart"]')
    NOTIFICATION_AB_ADDED = (By.XPATH, "//div[contains(text(), 'добавлен в корзину')]")
    SELECT_EMPLOYEE = (By.CSS_SELECTOR, '[data-qa="cart-select-employee"]')
    INPUT_EMPLOYEE = (By.CSS_SELECTOR, '[data-qa="cart-input-employee"]')
    SELECT_NAME = (By.CSS_SELECTOR, '[data-qa="cart-employee-suggest-first-el"]')
    PRICE_BUTTON = (By.CSS_SELECTOR, '[data-qa="cart-price-button"]')
    ACCEPT_RULES = (By.CSS_SELECTOR, '[data-qa="cart-checkout-finish-accept-rules"]')
    DUPLICATE_CARD = (By.CSS_SELECTOR, '[data-qa="cart-duplicate-button-back"]')
    DUPLICATE_BUTTON_CLOSE = (By.CSS_SELECTOR, '[data-qa="cart-duplicate-button-close"]')
    AGREEMENT = (By.XPATH, "//div[contains(text(), 'Всё верно')]")
    FINISH_BUY = (By.CSS_SELECTOR, '[data-qa="cart-checkout-finish-buy"]')
    PAY_DETAILS = (By.CSS_SELECTOR, '[data-qa="cart-checkout-success-pay-trip-details"]')
    TRIP_DETAILS = (By.XPATH, "//span[contains(text(), 'деталям')]")
    OPEN_TRIP = (By.XPATH, "//div[contains(text(), 'Вернуть')]")
    APPROVAL = (By.XPATH, "//div[contains(text(), 'Согласен')]")
    REFUND_TICKET = (By.CSS_SELECTOR, 'button[class="_button_26a8j_1 _primary_26a8j_26"]')
    CALCULATE_REFUND = (By.XPATH, "//span[contains(text(), 'Вернуть')]")
    CONFIRM_REFUND = (By.XPATH, '//span[contains(text(),"Подтверждаю возврат")]')
    WAIT_PROCESS_COMPLETE = (By.CSS_SELECTOR, '[class="_content_wrapper_1m4sy_4"]')
    CHECK_STATUS = (By.CSS_SELECTOR, '[class="_wrapper_1i2j8_1 _text_5fsuu_11 _default_1i2j8_2"]')
